version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    container_name: db

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      FLASK_ENV: development
      API_IRL: http://localhost:5000

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      NODE_ENV: development
      API_BASE_URL: http://localhost:5000

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - backend
      - frontend

  initdb:
    build: ./backend
    depends_on:
      - db
    command: ["./initdb.sh"]
    container_name: initdb
